/** English stop words — common words filtered from n-gram extraction. */
export const STOP_WORDS_EN = new Set([
  'a', 'an', 'the', 'and', 'or', 'but', 'if', 'in', 'on', 'at', 'to', 'for',
  'of', 'with', 'by', 'from', 'as', 'is', 'was', 'are', 'were', 'been', 'be',
  'have', 'has', 'had', 'do', 'does', 'did', 'will', 'would', 'could', 'should',
  'may', 'might', 'shall', 'can', 'need', 'dare', 'ought', 'used', 'not', 'no',
  'nor', 'so', 'yet', 'both', 'each', 'few', 'more', 'most', 'other', 'some',
  'such', 'than', 'too', 'very', 'just', 'about', 'above', 'after', 'again',
  'all', 'also', 'am', 'any', 'because', 'before', 'below', 'between', 'down',
  'during', 'even', 'every', 'further', 'get', 'got', 'here', 'how', 'i', 'im',
  'into', 'it', 'its', 'itself', 'me', 'my', 'myself', 'now', 'off', 'once',
  'only', 'our', 'out', 'over', 'own', 'same', 'she', 'he', 'her', 'him', 'his',
  'that', 'them', 'then', 'there', 'these', 'they', 'this', 'those', 'through',
  'under', 'until', 'up', 'us', 'we', 'what', 'when', 'where', 'which', 'while',
  'who', 'whom', 'why', 'you', 'your', 'yours', 'yourself', 'much', 'many',
  'like', 'going', 'gonna', 'dont', 'dont', 'didnt', 'cant', 'wont', 'isnt',
  'arent', 'wasnt', 'werent', 'hasnt', 'havent', 'hadnt', 'doesnt', 'shouldnt',
  'wouldnt', 'couldnt', 'mustnt', 'lets', 'thats', 'whos', 'whats', 'heres',
  'theres', 'whens', 'wheres', 'whys', 'hows', 'ive', 'youve', 'weve', 'theyve',
  'ill', 'youll', 'hell', 'shell', 'well', 'theyll', 'id', 'youd', 'hed',
  'shed', 'wed', 'theyd', 'really', 'still', 'already', 'always', 'never',
  'ever', 'thing', 'things', 'something', 'anything', 'nothing', 'everything',
  'someone', 'anyone', 'everyone', 'people', 'way', 'back', 'make', 'made',
  'know', 'think', 'see', 'look', 'want', 'give', 'use', 'find', 'tell',
  'say', 'said', 'one', 'two', 'new', 'good', 'first', 'last', 'long', 'great',
  'little', 'right', 'old', 'big', 'high', 'different', 'small', 'large',
  'next', 'early', 'young', 'important', 'another', 'being', 'lot', 'lol',
  'yeah', 'yes', 'okay', 'ok', 'oh', 'hey', 'hi', 'hello', 'thanks', 'thank',
  'please', 'sorry', 'well', 'actually', 'basically', 'literally', 'probably',
  'maybe', 'definitely', 'absolutely', 'exactly', 'simply', 'totally',
])
